blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path('', views.PostListView.as_view(), name="list"),
    path('<slug:slug>/', views.PostDetailView.as_view(), name="detail"),
]

store/urls.py
from django.urls import path

from . import views

app_name = "store"

urlpatterns = [
    path('', views.ProdutoListView.as_view(), name="list"),
    path('<slug:slug>/', views.ProdutoDetailView.as_view(), name="detail"),
]

tutorialdjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
   
    path('blog/', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
    path('', include("store.urls", namespace="pages")),
    
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

class Post(models.Model):

	title = models.CharField(max_length=255)
	slug = models.SlugField(max_length=255, unique=True)
	author = models.ForeignKey(User, on_delete= models.CASCADE)
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)	

	class Meta: 
		ordering = ("-created",)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("blog:detail", kwargs={"slug": self.slug})

store/models.py
from django.db import models
from django.urls import reverse

class Produto(models.Model):

	name = models.CharField(max_length=255)
	slug = models.SlugField(max_length=255, unique=True)
	price = models.DecimalField(max_digits=8, decimal_places=2)
	body  = models.TextField()
	image = models.CharField(max_length=255)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)	

	class Meta: 
		ordering = ("-created",)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse("store:detail", kwargs={"slug": self.slug})

blog/views.py
from django.views.generic import DetailView, ListView

from .models import Post

class PostListView(ListView):
	model = Post

class PostDetailView(DetailView):
	model = Post

store/views.py
from django.views.generic import DetailView, ListView

from .models import Produto

class ProdutoListView(ListView):
	model = Produto

class ProdutoDetailView(DetailView):
	model = Produto

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
	<title>Django Tutorial: {% block title %}{% endblock %}</title>
	<link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>

<body>

	<header>
		<h1>Blog do Django</h1>
	</header>
	
	<main>
		{% block content %}
		{% endblock %}
	</main>

</body>

</html>

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %} 
	
	<h2>{{ post.title}}</h2>
	<p class="date">
		Publicado em {{ post.created }} por {{ post.author }}
	</p>
	{{ post.body|linebreaks }}

{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block title %}Lista de Artigos{% endblock %}

{% block content %} 

	{% for post in post_list %}
	<article>
		<h2>
			<a href="{{ post.get_absolute_url }}">
				{{ post.title }}
			</a>
		</h2>

		<p class="date">
			Publicado em {{ post.created }} por {{ post.author }}
		</p>
		{{ post.body|linebreaks|truncatewords:10 }}
	</article>
	{% endfor %}

{% endblock %}

store/templates/store/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'store:list' %}">Python</a>
                <ul class="navbar-nav">
                     <li class="nav-item">
                        <a class="nav-link" href="/blog">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/admin">Login</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

store/templates/store/produto_detail.html
{% extends "store/base.html" %}
{% load mathfilters %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %} 
	
	<h2>{{ produto.name}}</h2>

	<img src="{{ produto.image }}" width="250px" height="250px">

	<h3>R$ {{ produto.price}}</h3>
	<h6>em 10x de R$ {{ produto.price|div:10 }} sem juros</h6>

	</br>

	<p class="date">
		Publicado em {{ produto.created }}
	</p>
	{{ produto.body|linebreaks }}

{% endblock %}

store/templates/store/produto_list.html
{% extends "store/base.html" %}
{% load mathfilters %}

{% block title %}Lista de Produtos{% endblock %}

{% block content %} 

	{% for produto in produto_list %}

	<article>

		<a href="{{ produto.get_absolute_url }}" style="float:left;">
			<img src="{{ produto.image }}" width="120px" height="120px">
		</a>

		<h2>
			<a href="{{ produto.get_absolute_url }}">
				{{ produto.name }}
			</a>
		</h2>

		<h5>por R$ {{ produto.price }}</h5>
		<h6>em 10x de R$ {{ produto.price|div:10 }} sem juros</h6>

	</article>


	{% endfor %}

{% endblock %}